CREATE TABLE pump_control (
  id INT PRIMARY KEY AUTO_INCREMENT,
  mode VARCHAR(10) DEFAULT 'auto',
  heater TINYINT(1) DEFAULT 0,
  fan TINYINT(1) DEFAULT 0,
  irrigation TINYINT(1) DEFAULT 0,
  refill TINYINT(1) DEFAULT 0,
  filter TINYINT(1) DEFAULT 0,
  updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

INSERT INTO pump_control (id, mode)
VALUES (1, 'auto')
ON DUPLICATE KEY UPDATE id = id;
